pipeline:
  build:
    
    npm_build:
      image: node:8
      environment:
        - NODE_ENV=production
      commands:
        - yarn install
        - yarn build

    deploy:
      image: node:8
      environment:
        - NODE_ENV=production
      commands:
        - echo "deployed!"
