pipeline:
  build:
    image: node:8
    environment:
      - NODE_ENV=development
    commands:
      - yarn install
      - touch private_configs.js
      - yarn build

  deploy:
    image: node:8
    environment:
      - NODE_ENV=production
    commands:
      - echo "deployed!"
