pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  build:
    image: node:8
    environment:
      - NODE_ENV=development
    commands:
      - yarn install --no-progress
      - touch private_configs.js
      - yarn build --release --docker

  publish:
    image: plugins/docker
    username: tobiasmayr
    repo: tobiasmayr/gold
    tags: [ dev ]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache