version: "3"
services:
  web:
    image: tobiasmayr/gold:dev
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 300M
      #restart_policy:
      #  condition: on-failure
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - NODE_ENV=production
      # connect to postgres running on the docker host
      - DATABASE_URL=postgresql://gold:gold@127.0.0.1:5432/gold
